/**
 * Imported essays manifest — auto-generated by content import.
 * Essays from Medium intake are merged into the atlas at build time.
 */
import * as essay_ai_loops_and_the_physics_of_awakening from "./essays/ai-loops-and-the-physics-of-awakening";
import * as essay_becoming_the_template from "./essays/becoming-the-template";
import * as essay_before_the_word_became_law from "./essays/before-the-word-became-law";
import * as essay_chronic_illness_is_a_paused_process_and_modern_medicine_keeps_hitting_fr from "./essays/chronic-illness-is-a-paused-process-and-modern-medicine-keeps-hitting-fr";
import * as essay_coming_online_the_shift_from_survival_mode_to_conscious_creation from "./essays/coming-online-the-shift-from-survival-mode-to-conscious-creation";
import * as essay_eden_was_a_warning from "./essays/eden-was-a-warning";
import * as essay_energy_systems_101_the_blueprint_behind_everything from "./essays/energy-systems-101-the-blueprint-behind-everything";
import * as essay_every_living_system_pays_a_maintenance_cost from "./essays/every-living-system-pays-a-maintenance-cost";
import * as essay_everyone_thinks_allergy_season_is_getting_stronger_but_what_if_our_barri from "./essays/everyone-thinks-allergy-season-is-getting-stronger-but-what-if-our-barri";
import * as essay_everything_you_know_about_the_heart_is_backwards from "./essays/everything-you-know-about-the-heart-is-backwards";
import * as essay_faithful_and_human from "./essays/faithful-and-human";
import * as essay_fragmentation_is_the_cost_of_symbolic_consciousness from "./essays/fragmentation-is-the-cost-of-symbolic-consciousness";
import * as essay_healing_is_the_gospel_and_the_body_already_knows_it from "./essays/healing-is-the-gospel-and-the-body-already-knows-it";
import * as essay_i_am_for_the_kids from "./essays/i-am-for-the-kids";
import * as essay_i_didn_t_write_a_psychedelic_book_i_wrote_an_orientation from "./essays/i-didn-t-write-a-psychedelic-book-i-wrote-an-orientation";
import * as essay_i_don_t_write_self_help_i_write_orientation from "./essays/i-don-t-write-self-help-i-write-orientation";
import * as essay_i_have_nothing_and_i_have_everything from "./essays/i-have-nothing-and-i-have-everything";
import * as essay_i_lost_my_innocence_a_few_years_ago from "./essays/i-lost-my-innocence-a-few-years-ago";
import * as essay_i_started_with_144_000 from "./essays/i-started-with-144-000";
import * as essay_i_stopped_explaining_myself_and_my_body_finally_exhaled from "./essays/i-stopped-explaining-myself-and-my-body-finally-exhaled";
import * as essay_i_thought_i_was_going_to_die_too from "./essays/i-thought-i-was-going-to-die-too";
import * as essay_i_tried_mushrooms_and_started_taking_notes from "./essays/i-tried-mushrooms-and-started-taking-notes";
import * as essay_i_ve_been_paying_attention from "./essays/i-ve-been-paying-attention";
import * as essay_i_ve_been_writing_in_the_dark from "./essays/i-ve-been-writing-in-the-dark";
import * as essay_i_wasn_t_trying_to_write_a_book_i_was_trying_to_save_my_life from "./essays/i-wasn-t-trying-to-write-a-book-i-was-trying-to-save-my-life";
import * as essay_if_the_moon_can_move_oceans_what_do_you_think_it_does_to_you from "./essays/if-the-moon-can-move-oceans-what-do-you-think-it-does-to-you";
import * as essay_if_you_feel_it_in_your_body_start_here from "./essays/if-you-feel-it-in-your-body-start-here";
import * as essay_medicine_is_learning_a_new_language from "./essays/medicine-is-learning-a-new-language";
import * as essay_my_body_woke_up_before_i_did from "./essays/my-body-woke-up-before-i-did";
import * as essay_my_father_saved_me_now_i_m_saving_the_lineage from "./essays/my-father-saved-me-now-i-m-saving-the-lineage";
import * as essay_my_healing_journey_accidentally_turned_into_a_study_of_consciousness from "./essays/my-healing-journey-accidentally-turned-into-a-study-of-consciousness";
import * as essay_nothing_is_new_only_remembered from "./essays/nothing-is-new-only-remembered";
import * as essay_nothing_is_outside_the_pattern_only_out_of_sync from "./essays/nothing-is-outside-the-pattern-only-out-of-sync";
import * as essay_noticing_patterns_isn_t_a_sin_forgetting_your_power_is from "./essays/noticing-patterns-isn-t-a-sin-forgetting-your-power-is";
import * as essay_optimization_without_nourishment from "./essays/optimization-without-nourishment";
import * as essay_parallel_lives_the_fire_and_the_feedback_loop from "./essays/parallel-lives-the-fire-and-the-feedback-loop";
import * as essay_parasites_programming_and_the_god_frequency from "./essays/parasites-programming-and-the-god-frequency";
import * as essay_preparation_vs_performance_what_happens_when_scarcity_returns from "./essays/preparation-vs-performance-what-happens-when-scarcity-returns";
import * as essay_psilocybin_helped_my_gut_as_much_as_diet_and_that_confused_me from "./essays/psilocybin-helped-my-gut-as-much-as-diet-and-that-confused-me";
import * as essay_regulation_is_not_calm from "./essays/regulation-is-not-calm";
import * as essay_seeing_humanity_as_a_system_changes_everything from "./essays/seeing-humanity-as-a-system-changes-everything";
import * as essay_signals_i_m_watching_june_2026 from "./essays/signals-i-m-watching-june-2026";
import * as essay_structure_is_stabilized_rhythm_across_time from "./essays/structure-is-stabilized-rhythm-across-time";
import * as essay_talking_into_the_void from "./essays/talking-into-the-void";
import * as essay_technology_was_never_separate_from_nature from "./essays/technology-was-never-separate-from-nature";
import * as essay_the_algorithmic_hijack_how_programs_and_patterns_replace_our_power from "./essays/the-algorithmic-hijack-how-programs-and-patterns-replace-our-power";
import * as essay_the_ancient_purpose_of_looking_up from "./essays/the-ancient-purpose-of-looking-up";
import * as essay_the_aquarius_full_moon_is_asking_us_one_question from "./essays/the-aquarius-full-moon-is-asking-us-one-question";
import * as essay_the_body_keeps_rhythm_because_reality_is_rhythmic from "./essays/the-body-keeps-rhythm-because-reality-is-rhythmic";
import * as essay_the_christ_story_moves_like_the_cosmos from "./essays/the-christ-story-moves-like-the-cosmos";
import * as essay_the_claustrophobia_of_consciousness_when_awareness_becomes_the_hardest_t from "./essays/the-claustrophobia-of-consciousness-when-awareness-becomes-the-hardest-t";
import * as essay_the_collapse_of_internal_authority from "./essays/the-collapse-of-internal-authority";
import * as essay_the_decomposition_response from "./essays/the-decomposition-response";
import * as essay_the_difference_between_restraint_and_regulation from "./essays/the-difference-between-restraint-and-regulation";
import * as essay_the_evolution_of_language from "./essays/the-evolution-of-language";
import * as essay_the_evolution_of_religions_why_every_age_has_its_messiahs from "./essays/the-evolution-of-religions-why-every-age-has-its-messiahs";
import * as essay_the_forgotten_structure_of_reality from "./essays/the-forgotten-structure-of-reality";
import * as essay_the_future_of_healthcare_5_predictions from "./essays/the-future-of-healthcare-5-predictions";
import * as essay_the_girl_who_watched_tv_upside_down from "./essays/the-girl-who-watched-tv-upside-down";
import * as essay_the_goal_was_never_restriction from "./essays/the-goal-was-never-restriction";
import * as essay_the_god_code_why_ai_feels_so_threatening_and_why_it_shouldn_t from "./essays/the-god-code-why-ai-feels-so-threatening-and-why-it-shouldn-t";
import * as essay_the_illusion_of_purity_is_cracking from "./essays/the-illusion-of-purity-is-cracking";
import * as essay_the_integration_wave from "./essays/the-integration-wave";
import * as essay_the_kingdom_of_god_is_a_regulated_nervous_system from "./essays/the-kingdom-of-god-is-a-regulated-nervous-system";
import * as essay_the_kitchen_we_quietly_lost from "./essays/the-kitchen-we-quietly-lost";
import * as essay_the_most_addictive_thing_in_your_life_may_be_familiar_stress from "./essays/the-most-addictive-thing-in-your-life-may-be-familiar-stress";
import * as essay_the_most_important_thing_you_never_learned_about_reality from "./essays/the-most-important-thing-you-never-learned-about-reality";
import * as essay_the_nervous_system_doesn_t_know_it_s_january from "./essays/the-nervous-system-doesn-t-know-it-s-january";
import * as essay_the_normalization_problem from "./essays/the-normalization-problem";
import * as essay_the_opposite_side_rule from "./essays/the-opposite-side-rule";
import * as essay_the_planetary_awakening from "./essays/the-planetary-awakening";
import * as essay_the_question_that_changed_everything from "./essays/the-question-that-changed-everything";
import * as essay_the_revolution_after_ai from "./essays/the-revolution-after-ai";
import * as essay_the_roman_system_the_divine_feminine_and_the_collapse_of_modern_health from "./essays/the-roman-system-the-divine-feminine-and-the-collapse-of-modern-health";
import * as essay_the_second_printing_press from "./essays/the-second-printing-press";
import * as essay_the_second_time_i_thought_i_was_going_to_die from "./essays/the-second-time-i-thought-i-was-going-to-die";
import * as essay_the_signal_everyone_is_trying_to_replace from "./essays/the-signal-everyone-is-trying-to-replace";
import * as essay_the_silent_epidemic_of_dissolving_barriers from "./essays/the-silent-epidemic-of-dissolving-barriers";
import * as essay_the_smart_loop_why_awakening_isn_t_mystical from "./essays/the-smart-loop-why-awakening-isn-t-mystical";
import * as essay_the_systems_we_mistake_for_reality from "./essays/the-systems-we-mistake-for-reality";
import * as essay_the_valve_is_cracking_the_limits_of_reductionist_medicine from "./essays/the-valve-is-cracking-the-limits-of-reductionist-medicine";
import * as essay_the_wall_of_consciousness from "./essays/the-wall-of-consciousness";
import * as essay_the_way_was_greater_than_me from "./essays/the-way-was-greater-than-me";
import * as essay_the_work_no_one_sees_when_love_is_finally_safe from "./essays/the-work-no-one-sees-when-love-is-finally-safe";
import * as essay_the_wrong_question_about_transhumanism from "./essays/the-wrong-question-about-transhumanism";
import * as essay_there_is_a_cost_to_becoming_an_image from "./essays/there-is-a-cost-to-becoming-an-image";
import * as essay_this_is_not_the_end_of_corruption_this_is_the_end_of_innocence from "./essays/this-is-not-the-end-of-corruption-this-is-the-end-of-innocence";
import * as essay_this_isn_t_polarization_it_s_sorting from "./essays/this-isn-t-polarization-it-s-sorting";
import * as essay_uranus_entered_gemini_the_next_era_may_be_hard_on_the_human_nervous_syst from "./essays/uranus-entered-gemini-the-next-era-may-be-hard-on-the-human-nervous-syst";
import * as essay_we_are_not_separate_from_the_earth_we_are_the_earth from "./essays/we-are-not-separate-from-the-earth-we-are-the-earth";
import * as essay_we_weren_t_eating_we_were_coping from "./essays/we-weren-t-eating-we-were-coping";
import * as essay_what_had_to_happen_for_this_to_exist from "./essays/what-had-to-happen-for-this-to-exist";
import * as essay_what_happens_before_the_tragedy from "./essays/what-happens-before-the-tragedy";
import * as essay_what_if_numbers_are_a_language from "./essays/what-if-numbers-are-a-language";
import * as essay_what_philosophers_understood_about_suffering_before_biology_could_explai from "./essays/what-philosophers-understood-about-suffering-before-biology-could-explai";
import * as essay_what_your_nervous_system_is_doing_leading_up_to_the_full_moon from "./essays/what-your-nervous-system-is-doing-leading-up-to-the-full-moon";
import * as essay_when_meaning_arrives_too_fast from "./essays/when-meaning-arrives-too-fast";
import * as essay_when_optimization_replaced_wisdom from "./essays/when-optimization-replaced-wisdom";
import * as essay_when_sacrifice_stops_leading_somewhere from "./essays/when-sacrifice-stops-leading-somewhere";
import * as essay_when_structure_outpaces_awareness from "./essays/when-structure-outpaces-awareness";
import * as essay_when_the_internet_gets_too_loud_to_think from "./essays/when-the-internet-gets-too-loud-to-think";
import * as essay_when_the_map_becomes_the_blind_spot from "./essays/when-the-map-becomes-the-blind-spot";
import * as essay_when_the_spirit_drags_the_body from "./essays/when-the-spirit-drags-the-body";
import * as essay_who_buried_the_truth from "./essays/who-buried-the-truth";
import * as essay_why_healers_exist_and_why_information_isn_t_enough from "./essays/why-healers-exist-and-why-information-isn-t-enough";
import * as essay_why_marijuana_feels_like_relief_in_a_world_that_won_t_let_you_rest from "./essays/why-marijuana-feels-like-relief-in-a-world-that-won-t-let-you-rest";
import * as essay_why_modern_life_feels_so_unreal from "./essays/why-modern-life-feels-so-unreal";
import * as essay_why_people_give_up_forgetting_why_they_chose_the_pain from "./essays/why-people-give-up-forgetting-why-they-chose-the-pain";
import * as essay_why_some_people_want_instructions_instead_of_healing from "./essays/why-some-people-want-instructions-instead-of-healing";
import * as essay_why_the_bible_still_feels_relevant from "./essays/why-the-bible-still-feels-relevant";
import * as essay_writing_is_coming_back from "./essays/writing-is-coming-back";
import * as essay_writing_without_permission from "./essays/writing-without-permission";
import * as essay_yes_i_am_sensitive from "./essays/yes-i-am-sensitive";
import * as essay_you_cannot_heal_in_the_same_state_that_made_you_sick from "./essays/you-cannot-heal-in-the-same-state-that-made-you-sick";
import * as essay_you_don_t_sound_human_enough_anymore from "./essays/you-don-t-sound-human-enough-anymore";
import * as essay_you_have_power_how_experience_rewrites_your_biology from "./essays/you-have-power-how-experience-rewrites-your-biology";
import * as essay_you_re_not_afraid_of_rejection_you_re_afraid_of_death from "./essays/you-re-not-afraid-of-rejection-you-re-afraid-of-death";
import * as essay_your_body_is_not_a_machine_it_s_an_ecosystem from "./essays/your-body-is-not-a-machine-it-s-an-ecosystem";

import {
  IMPORTED_BOOK_CONNECTIONS,
  IMPORTED_BOOK_ENTRIES,
} from "./books";
import type { AtlasConnection, AtlasEntry } from "../types";

export const IMPORTED_ESSAY_ENTRIES: AtlasEntry[] = [
  essay_ai_loops_and_the_physics_of_awakening.ENTRY,
  essay_becoming_the_template.ENTRY,
  essay_before_the_word_became_law.ENTRY,
  essay_chronic_illness_is_a_paused_process_and_modern_medicine_keeps_hitting_fr.ENTRY,
  essay_coming_online_the_shift_from_survival_mode_to_conscious_creation.ENTRY,
  essay_eden_was_a_warning.ENTRY,
  essay_energy_systems_101_the_blueprint_behind_everything.ENTRY,
  essay_every_living_system_pays_a_maintenance_cost.ENTRY,
  essay_everyone_thinks_allergy_season_is_getting_stronger_but_what_if_our_barri.ENTRY,
  essay_everything_you_know_about_the_heart_is_backwards.ENTRY,
  essay_faithful_and_human.ENTRY,
  essay_fragmentation_is_the_cost_of_symbolic_consciousness.ENTRY,
  essay_healing_is_the_gospel_and_the_body_already_knows_it.ENTRY,
  essay_i_am_for_the_kids.ENTRY,
  essay_i_didn_t_write_a_psychedelic_book_i_wrote_an_orientation.ENTRY,
  essay_i_don_t_write_self_help_i_write_orientation.ENTRY,
  essay_i_have_nothing_and_i_have_everything.ENTRY,
  essay_i_lost_my_innocence_a_few_years_ago.ENTRY,
  essay_i_started_with_144_000.ENTRY,
  essay_i_stopped_explaining_myself_and_my_body_finally_exhaled.ENTRY,
  essay_i_thought_i_was_going_to_die_too.ENTRY,
  essay_i_tried_mushrooms_and_started_taking_notes.ENTRY,
  essay_i_ve_been_paying_attention.ENTRY,
  essay_i_ve_been_writing_in_the_dark.ENTRY,
  essay_i_wasn_t_trying_to_write_a_book_i_was_trying_to_save_my_life.ENTRY,
  essay_if_the_moon_can_move_oceans_what_do_you_think_it_does_to_you.ENTRY,
  essay_if_you_feel_it_in_your_body_start_here.ENTRY,
  essay_medicine_is_learning_a_new_language.ENTRY,
  essay_my_body_woke_up_before_i_did.ENTRY,
  essay_my_father_saved_me_now_i_m_saving_the_lineage.ENTRY,
  essay_my_healing_journey_accidentally_turned_into_a_study_of_consciousness.ENTRY,
  essay_nothing_is_new_only_remembered.ENTRY,
  essay_nothing_is_outside_the_pattern_only_out_of_sync.ENTRY,
  essay_noticing_patterns_isn_t_a_sin_forgetting_your_power_is.ENTRY,
  essay_optimization_without_nourishment.ENTRY,
  essay_parallel_lives_the_fire_and_the_feedback_loop.ENTRY,
  essay_parasites_programming_and_the_god_frequency.ENTRY,
  essay_preparation_vs_performance_what_happens_when_scarcity_returns.ENTRY,
  essay_psilocybin_helped_my_gut_as_much_as_diet_and_that_confused_me.ENTRY,
  essay_regulation_is_not_calm.ENTRY,
  essay_seeing_humanity_as_a_system_changes_everything.ENTRY,
  essay_signals_i_m_watching_june_2026.ENTRY,
  essay_structure_is_stabilized_rhythm_across_time.ENTRY,
  essay_talking_into_the_void.ENTRY,
  essay_technology_was_never_separate_from_nature.ENTRY,
  essay_the_algorithmic_hijack_how_programs_and_patterns_replace_our_power.ENTRY,
  essay_the_ancient_purpose_of_looking_up.ENTRY,
  essay_the_aquarius_full_moon_is_asking_us_one_question.ENTRY,
  essay_the_body_keeps_rhythm_because_reality_is_rhythmic.ENTRY,
  essay_the_christ_story_moves_like_the_cosmos.ENTRY,
  essay_the_claustrophobia_of_consciousness_when_awareness_becomes_the_hardest_t.ENTRY,
  essay_the_collapse_of_internal_authority.ENTRY,
  essay_the_decomposition_response.ENTRY,
  essay_the_difference_between_restraint_and_regulation.ENTRY,
  essay_the_evolution_of_language.ENTRY,
  essay_the_evolution_of_religions_why_every_age_has_its_messiahs.ENTRY,
  essay_the_forgotten_structure_of_reality.ENTRY,
  essay_the_future_of_healthcare_5_predictions.ENTRY,
  essay_the_girl_who_watched_tv_upside_down.ENTRY,
  essay_the_goal_was_never_restriction.ENTRY,
  essay_the_god_code_why_ai_feels_so_threatening_and_why_it_shouldn_t.ENTRY,
  essay_the_illusion_of_purity_is_cracking.ENTRY,
  essay_the_integration_wave.ENTRY,
  essay_the_kingdom_of_god_is_a_regulated_nervous_system.ENTRY,
  essay_the_kitchen_we_quietly_lost.ENTRY,
  essay_the_most_addictive_thing_in_your_life_may_be_familiar_stress.ENTRY,
  essay_the_most_important_thing_you_never_learned_about_reality.ENTRY,
  essay_the_nervous_system_doesn_t_know_it_s_january.ENTRY,
  essay_the_normalization_problem.ENTRY,
  essay_the_opposite_side_rule.ENTRY,
  essay_the_planetary_awakening.ENTRY,
  essay_the_question_that_changed_everything.ENTRY,
  essay_the_revolution_after_ai.ENTRY,
  essay_the_roman_system_the_divine_feminine_and_the_collapse_of_modern_health.ENTRY,
  essay_the_second_printing_press.ENTRY,
  essay_the_second_time_i_thought_i_was_going_to_die.ENTRY,
  essay_the_signal_everyone_is_trying_to_replace.ENTRY,
  essay_the_silent_epidemic_of_dissolving_barriers.ENTRY,
  essay_the_smart_loop_why_awakening_isn_t_mystical.ENTRY,
  essay_the_systems_we_mistake_for_reality.ENTRY,
  essay_the_valve_is_cracking_the_limits_of_reductionist_medicine.ENTRY,
  essay_the_wall_of_consciousness.ENTRY,
  essay_the_way_was_greater_than_me.ENTRY,
  essay_the_work_no_one_sees_when_love_is_finally_safe.ENTRY,
  essay_the_wrong_question_about_transhumanism.ENTRY,
  essay_there_is_a_cost_to_becoming_an_image.ENTRY,
  essay_this_is_not_the_end_of_corruption_this_is_the_end_of_innocence.ENTRY,
  essay_this_isn_t_polarization_it_s_sorting.ENTRY,
  essay_uranus_entered_gemini_the_next_era_may_be_hard_on_the_human_nervous_syst.ENTRY,
  essay_we_are_not_separate_from_the_earth_we_are_the_earth.ENTRY,
  essay_we_weren_t_eating_we_were_coping.ENTRY,
  essay_what_had_to_happen_for_this_to_exist.ENTRY,
  essay_what_happens_before_the_tragedy.ENTRY,
  essay_what_if_numbers_are_a_language.ENTRY,
  essay_what_philosophers_understood_about_suffering_before_biology_could_explai.ENTRY,
  essay_what_your_nervous_system_is_doing_leading_up_to_the_full_moon.ENTRY,
  essay_when_meaning_arrives_too_fast.ENTRY,
  essay_when_optimization_replaced_wisdom.ENTRY,
  essay_when_sacrifice_stops_leading_somewhere.ENTRY,
  essay_when_structure_outpaces_awareness.ENTRY,
  essay_when_the_internet_gets_too_loud_to_think.ENTRY,
  essay_when_the_map_becomes_the_blind_spot.ENTRY,
  essay_when_the_spirit_drags_the_body.ENTRY,
  essay_who_buried_the_truth.ENTRY,
  essay_why_healers_exist_and_why_information_isn_t_enough.ENTRY,
  essay_why_marijuana_feels_like_relief_in_a_world_that_won_t_let_you_rest.ENTRY,
  essay_why_modern_life_feels_so_unreal.ENTRY,
  essay_why_people_give_up_forgetting_why_they_chose_the_pain.ENTRY,
  essay_why_some_people_want_instructions_instead_of_healing.ENTRY,
  essay_why_the_bible_still_feels_relevant.ENTRY,
  essay_writing_is_coming_back.ENTRY,
  essay_writing_without_permission.ENTRY,
  essay_yes_i_am_sensitive.ENTRY,
  essay_you_cannot_heal_in_the_same_state_that_made_you_sick.ENTRY,
  essay_you_don_t_sound_human_enough_anymore.ENTRY,
  essay_you_have_power_how_experience_rewrites_your_biology.ENTRY,
  essay_you_re_not_afraid_of_rejection_you_re_afraid_of_death.ENTRY,
  essay_your_body_is_not_a_machine_it_s_an_ecosystem.ENTRY,
];

export { IMPORTED_BOOK_ENTRIES, IMPORTED_BOOK_CONNECTIONS };

export const IMPORTED_ESSAY_CONNECTIONS: AtlasConnection[] = [
  ...essay_ai_loops_and_the_physics_of_awakening.CONNECTIONS,
  ...essay_becoming_the_template.CONNECTIONS,
  ...essay_before_the_word_became_law.CONNECTIONS,
  ...essay_chronic_illness_is_a_paused_process_and_modern_medicine_keeps_hitting_fr.CONNECTIONS,
  ...essay_coming_online_the_shift_from_survival_mode_to_conscious_creation.CONNECTIONS,
  ...essay_eden_was_a_warning.CONNECTIONS,
  ...essay_energy_systems_101_the_blueprint_behind_everything.CONNECTIONS,
  ...essay_every_living_system_pays_a_maintenance_cost.CONNECTIONS,
  ...essay_everyone_thinks_allergy_season_is_getting_stronger_but_what_if_our_barri.CONNECTIONS,
  ...essay_everything_you_know_about_the_heart_is_backwards.CONNECTIONS,
  ...essay_faithful_and_human.CONNECTIONS,
  ...essay_fragmentation_is_the_cost_of_symbolic_consciousness.CONNECTIONS,
  ...essay_healing_is_the_gospel_and_the_body_already_knows_it.CONNECTIONS,
  ...essay_i_am_for_the_kids.CONNECTIONS,
  ...essay_i_didn_t_write_a_psychedelic_book_i_wrote_an_orientation.CONNECTIONS,
  ...essay_i_don_t_write_self_help_i_write_orientation.CONNECTIONS,
  ...essay_i_have_nothing_and_i_have_everything.CONNECTIONS,
  ...essay_i_lost_my_innocence_a_few_years_ago.CONNECTIONS,
  ...essay_i_started_with_144_000.CONNECTIONS,
  ...essay_i_stopped_explaining_myself_and_my_body_finally_exhaled.CONNECTIONS,
  ...essay_i_thought_i_was_going_to_die_too.CONNECTIONS,
  ...essay_i_tried_mushrooms_and_started_taking_notes.CONNECTIONS,
  ...essay_i_ve_been_paying_attention.CONNECTIONS,
  ...essay_i_ve_been_writing_in_the_dark.CONNECTIONS,
  ...essay_i_wasn_t_trying_to_write_a_book_i_was_trying_to_save_my_life.CONNECTIONS,
  ...essay_if_the_moon_can_move_oceans_what_do_you_think_it_does_to_you.CONNECTIONS,
  ...essay_if_you_feel_it_in_your_body_start_here.CONNECTIONS,
  ...essay_medicine_is_learning_a_new_language.CONNECTIONS,
  ...essay_my_body_woke_up_before_i_did.CONNECTIONS,
  ...essay_my_father_saved_me_now_i_m_saving_the_lineage.CONNECTIONS,
  ...essay_my_healing_journey_accidentally_turned_into_a_study_of_consciousness.CONNECTIONS,
  ...essay_nothing_is_new_only_remembered.CONNECTIONS,
  ...essay_nothing_is_outside_the_pattern_only_out_of_sync.CONNECTIONS,
  ...essay_noticing_patterns_isn_t_a_sin_forgetting_your_power_is.CONNECTIONS,
  ...essay_optimization_without_nourishment.CONNECTIONS,
  ...essay_parallel_lives_the_fire_and_the_feedback_loop.CONNECTIONS,
  ...essay_parasites_programming_and_the_god_frequency.CONNECTIONS,
  ...essay_preparation_vs_performance_what_happens_when_scarcity_returns.CONNECTIONS,
  ...essay_psilocybin_helped_my_gut_as_much_as_diet_and_that_confused_me.CONNECTIONS,
  ...essay_regulation_is_not_calm.CONNECTIONS,
  ...essay_seeing_humanity_as_a_system_changes_everything.CONNECTIONS,
  ...essay_signals_i_m_watching_june_2026.CONNECTIONS,
  ...essay_structure_is_stabilized_rhythm_across_time.CONNECTIONS,
  ...essay_talking_into_the_void.CONNECTIONS,
  ...essay_technology_was_never_separate_from_nature.CONNECTIONS,
  ...essay_the_algorithmic_hijack_how_programs_and_patterns_replace_our_power.CONNECTIONS,
  ...essay_the_ancient_purpose_of_looking_up.CONNECTIONS,
  ...essay_the_aquarius_full_moon_is_asking_us_one_question.CONNECTIONS,
  ...essay_the_body_keeps_rhythm_because_reality_is_rhythmic.CONNECTIONS,
  ...essay_the_christ_story_moves_like_the_cosmos.CONNECTIONS,
  ...essay_the_claustrophobia_of_consciousness_when_awareness_becomes_the_hardest_t.CONNECTIONS,
  ...essay_the_collapse_of_internal_authority.CONNECTIONS,
  ...essay_the_decomposition_response.CONNECTIONS,
  ...essay_the_difference_between_restraint_and_regulation.CONNECTIONS,
  ...essay_the_evolution_of_language.CONNECTIONS,
  ...essay_the_evolution_of_religions_why_every_age_has_its_messiahs.CONNECTIONS,
  ...essay_the_forgotten_structure_of_reality.CONNECTIONS,
  ...essay_the_future_of_healthcare_5_predictions.CONNECTIONS,
  ...essay_the_girl_who_watched_tv_upside_down.CONNECTIONS,
  ...essay_the_goal_was_never_restriction.CONNECTIONS,
  ...essay_the_god_code_why_ai_feels_so_threatening_and_why_it_shouldn_t.CONNECTIONS,
  ...essay_the_illusion_of_purity_is_cracking.CONNECTIONS,
  ...essay_the_integration_wave.CONNECTIONS,
  ...essay_the_kingdom_of_god_is_a_regulated_nervous_system.CONNECTIONS,
  ...essay_the_kitchen_we_quietly_lost.CONNECTIONS,
  ...essay_the_most_addictive_thing_in_your_life_may_be_familiar_stress.CONNECTIONS,
  ...essay_the_most_important_thing_you_never_learned_about_reality.CONNECTIONS,
  ...essay_the_nervous_system_doesn_t_know_it_s_january.CONNECTIONS,
  ...essay_the_normalization_problem.CONNECTIONS,
  ...essay_the_opposite_side_rule.CONNECTIONS,
  ...essay_the_planetary_awakening.CONNECTIONS,
  ...essay_the_question_that_changed_everything.CONNECTIONS,
  ...essay_the_revolution_after_ai.CONNECTIONS,
  ...essay_the_roman_system_the_divine_feminine_and_the_collapse_of_modern_health.CONNECTIONS,
  ...essay_the_second_printing_press.CONNECTIONS,
  ...essay_the_second_time_i_thought_i_was_going_to_die.CONNECTIONS,
  ...essay_the_signal_everyone_is_trying_to_replace.CONNECTIONS,
  ...essay_the_silent_epidemic_of_dissolving_barriers.CONNECTIONS,
  ...essay_the_smart_loop_why_awakening_isn_t_mystical.CONNECTIONS,
  ...essay_the_systems_we_mistake_for_reality.CONNECTIONS,
  ...essay_the_valve_is_cracking_the_limits_of_reductionist_medicine.CONNECTIONS,
  ...essay_the_wall_of_consciousness.CONNECTIONS,
  ...essay_the_way_was_greater_than_me.CONNECTIONS,
  ...essay_the_work_no_one_sees_when_love_is_finally_safe.CONNECTIONS,
  ...essay_the_wrong_question_about_transhumanism.CONNECTIONS,
  ...essay_there_is_a_cost_to_becoming_an_image.CONNECTIONS,
  ...essay_this_is_not_the_end_of_corruption_this_is_the_end_of_innocence.CONNECTIONS,
  ...essay_this_isn_t_polarization_it_s_sorting.CONNECTIONS,
  ...essay_uranus_entered_gemini_the_next_era_may_be_hard_on_the_human_nervous_syst.CONNECTIONS,
  ...essay_we_are_not_separate_from_the_earth_we_are_the_earth.CONNECTIONS,
  ...essay_we_weren_t_eating_we_were_coping.CONNECTIONS,
  ...essay_what_had_to_happen_for_this_to_exist.CONNECTIONS,
  ...essay_what_happens_before_the_tragedy.CONNECTIONS,
  ...essay_what_if_numbers_are_a_language.CONNECTIONS,
  ...essay_what_philosophers_understood_about_suffering_before_biology_could_explai.CONNECTIONS,
  ...essay_what_your_nervous_system_is_doing_leading_up_to_the_full_moon.CONNECTIONS,
  ...essay_when_meaning_arrives_too_fast.CONNECTIONS,
  ...essay_when_optimization_replaced_wisdom.CONNECTIONS,
  ...essay_when_sacrifice_stops_leading_somewhere.CONNECTIONS,
  ...essay_when_structure_outpaces_awareness.CONNECTIONS,
  ...essay_when_the_internet_gets_too_loud_to_think.CONNECTIONS,
  ...essay_when_the_map_becomes_the_blind_spot.CONNECTIONS,
  ...essay_when_the_spirit_drags_the_body.CONNECTIONS,
  ...essay_who_buried_the_truth.CONNECTIONS,
  ...essay_why_healers_exist_and_why_information_isn_t_enough.CONNECTIONS,
  ...essay_why_marijuana_feels_like_relief_in_a_world_that_won_t_let_you_rest.CONNECTIONS,
  ...essay_why_modern_life_feels_so_unreal.CONNECTIONS,
  ...essay_why_people_give_up_forgetting_why_they_chose_the_pain.CONNECTIONS,
  ...essay_why_some_people_want_instructions_instead_of_healing.CONNECTIONS,
  ...essay_why_the_bible_still_feels_relevant.CONNECTIONS,
  ...essay_writing_is_coming_back.CONNECTIONS,
  ...essay_writing_without_permission.CONNECTIONS,
  ...essay_yes_i_am_sensitive.CONNECTIONS,
  ...essay_you_cannot_heal_in_the_same_state_that_made_you_sick.CONNECTIONS,
  ...essay_you_don_t_sound_human_enough_anymore.CONNECTIONS,
  ...essay_you_have_power_how_experience_rewrites_your_biology.CONNECTIONS,
  ...essay_you_re_not_afraid_of_rejection_you_re_afraid_of_death.CONNECTIONS,
  ...essay_your_body_is_not_a_machine_it_s_an_ecosystem.CONNECTIONS,
];
