/**
 * Imported essays manifest — auto-generated by content import.
 * Essays from Medium intake are merged into the atlas at build time.
 */
import * as essay_every_living_system_pays_a_maintenance_cost from "./essays/every-living-system-pays-a-maintenance-cost";
import * as essay_if_you_feel_it_in_your_body_start_here from "./essays/if-you-feel-it-in-your-body-start-here";
import * as essay_signals_i_m_watching_june_2026 from "./essays/signals-i-m-watching-june-2026";
import * as essay_the_ancient_purpose_of_looking_up from "./essays/the-ancient-purpose-of-looking-up";
import * as essay_the_goal_was_never_restriction from "./essays/the-goal-was-never-restriction";
import * as essay_the_most_important_thing_you_never_learned_about_reality from "./essays/the-most-important-thing-you-never-learned-about-reality";
import * as essay_there_is_a_cost_to_becoming_an_image from "./essays/there-is-a-cost-to-becoming-an-image";
import * as essay_what_happens_before_the_tragedy from "./essays/what-happens-before-the-tragedy";
import * as essay_when_sacrifice_stops_leading_somewhere from "./essays/when-sacrifice-stops-leading-somewhere";

import {
  IMPORTED_BOOK_CONNECTIONS,
  IMPORTED_BOOK_ENTRIES,
} from "./books";
import type { AtlasConnection, AtlasEntry } from "../types";

export const IMPORTED_ESSAY_ENTRIES: AtlasEntry[] = [
  essay_every_living_system_pays_a_maintenance_cost.ENTRY,
  essay_if_you_feel_it_in_your_body_start_here.ENTRY,
  essay_signals_i_m_watching_june_2026.ENTRY,
  essay_the_ancient_purpose_of_looking_up.ENTRY,
  essay_the_goal_was_never_restriction.ENTRY,
  essay_the_most_important_thing_you_never_learned_about_reality.ENTRY,
  essay_there_is_a_cost_to_becoming_an_image.ENTRY,
  essay_what_happens_before_the_tragedy.ENTRY,
  essay_when_sacrifice_stops_leading_somewhere.ENTRY,
];

export { IMPORTED_BOOK_ENTRIES, IMPORTED_BOOK_CONNECTIONS };

export const IMPORTED_ESSAY_CONNECTIONS: AtlasConnection[] = [
  ...essay_every_living_system_pays_a_maintenance_cost.CONNECTIONS,
  ...essay_if_you_feel_it_in_your_body_start_here.CONNECTIONS,
  ...essay_signals_i_m_watching_june_2026.CONNECTIONS,
  ...essay_the_ancient_purpose_of_looking_up.CONNECTIONS,
  ...essay_the_goal_was_never_restriction.CONNECTIONS,
  ...essay_the_most_important_thing_you_never_learned_about_reality.CONNECTIONS,
  ...essay_there_is_a_cost_to_becoming_an_image.CONNECTIONS,
  ...essay_what_happens_before_the_tragedy.CONNECTIONS,
  ...essay_when_sacrifice_stops_leading_somewhere.CONNECTIONS,
];
