import fs from "node:fs";
import path from "node:path";
import type { AtlasConnection, AtlasEntry } from "../atlas/types";
import type { ApplyResult, EssayImportPlan } from "./types";
import { INTAKE_ROOT } from "./load-intake";

const IMPORTS_DIR = path.join(process.cwd(), "lib/atlas/imports/essays");
const MANIFEST_PATH = path.join(process.cwd(), "lib/atlas/imports/index.ts");
const IMAGES_DIR = path.join(process.cwd(), "public/images/essays");
const APPLIED_DIR = path.join(INTAKE_ROOT, "applied");
const PREVIEW_DIR = path.join(INTAKE_ROOT, "preview");

function serializeEntry(entry: AtlasEntry): string {
  return JSON.stringify(entry, null, 2)
    .replace(/"([^"]+)":/g, "$1:")
    .replace(/"/g, '"');
}

/** Emit TypeScript source for one imported essay */
function emitEssayModule(plan: EssayImportPlan): string {
  const entryJson = JSON.stringify(plan.entry, null, 2);
  const connectionsJson = JSON.stringify(plan.connections, null, 2);

  return `/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: ${plan.slug}.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = ${entryJson};

export const CONNECTIONS: AtlasConnection[] = ${connectionsJson};
`;
}

function regenerateManifest(): void {
  if (!fs.existsSync(IMPORTS_DIR)) {
    fs.mkdirSync(IMPORTS_DIR, { recursive: true });
  }

  const modules = fs
    .readdirSync(IMPORTS_DIR)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();

  const imports = modules
    .map((slug) => `import * as essay_${slug.replace(/-/g, "_")} from "./essays/${slug}";`)
    .join("\n");

  const entries = modules
    .map((slug) => `  essay_${slug.replace(/-/g, "_")}.ENTRY,`)
    .join("\n");

  const connections = modules
    .map(
      (slug) =>
        `  ...essay_${slug.replace(/-/g, "_")}.CONNECTIONS,`,
    )
    .join("\n");

  const content = `/**
 * Imported essays manifest — auto-generated by content import.
 * Essays from Medium intake are merged into the atlas at build time.
 */
${imports || "// No imported essays yet"}

import type { AtlasConnection, AtlasEntry } from "../types";

export const IMPORTED_ESSAY_ENTRIES: AtlasEntry[] = [
${entries}
];

export const IMPORTED_ESSAY_CONNECTIONS: AtlasConnection[] = [
${connections}
];
`;

  fs.writeFileSync(MANIFEST_PATH, content, "utf8");
}

export async function applyEssayImportPlan(
  plan: EssayImportPlan,
  options: {
    intakePath?: string;
    archiveIntake?: boolean;
    copyImage?: boolean;
  } = {},
): Promise<ApplyResult> {
  const { archiveIntake = true, copyImage = true } = options;

  fs.mkdirSync(IMPORTS_DIR, { recursive: true });
  fs.mkdirSync(PREVIEW_DIR, { recursive: true });

  const entryFile = path.join(IMPORTS_DIR, `${plan.slug}.ts`);
  if (fs.existsSync(entryFile)) {
    throw new Error(
      `Essay "${plan.slug}" already imported at ${entryFile}. Remove it first or use overrides.slug.`,
    );
  }

  fs.writeFileSync(entryFile, emitEssayModule(plan), "utf8");
  regenerateManifest();

  fs.writeFileSync(
    path.join(PREVIEW_DIR, `${plan.slug}.plan.json`),
    JSON.stringify(plan, null, 2),
    "utf8",
  );

  let imageCopied = false;
  if (copyImage && plan.featuredImage) {
    fs.mkdirSync(IMAGES_DIR, { recursive: true });
    const dest = path.join(IMAGES_DIR, `${plan.slug}.jpg`);
    if (fs.existsSync(plan.featuredImage.sourcePath)) {
      fs.copyFileSync(plan.featuredImage.sourcePath, dest);
      imageCopied = true;
    }
  }

  let intakeArchivedTo: string | undefined;
  if (archiveIntake && options.intakePath && fs.existsSync(options.intakePath)) {
    fs.mkdirSync(APPLIED_DIR, { recursive: true });
    intakeArchivedTo = path.join(APPLIED_DIR, path.basename(options.intakePath));
    fs.renameSync(options.intakePath, intakeArchivedTo);
  }

  return {
    plan,
    entryFile,
    manifestUpdated: true,
    imageCopied,
    intakeArchivedTo,
  };
}
