#!/usr/bin/env npx tsx
/**
 * Read-only publication drift report for Atlas essay records that have a
 * verified Substack counterpart in the publication registry. Writes only
 * reports/publication-drift.{json,md}; never changes Atlas or registry data.
 */
import fs from "node:fs";
import path from "node:path";
import aliasesRegistry from "../data/publications/substack-aliases.json";
import identityDecisions from "../data/publications/identity-decisions.json";
import postsRegistry from "../data/publications/substack-posts.json";
import { getAtlas, toEssay } from "../lib/atlas";
import type { IdentityDecisionRegistry } from "../lib/content-sync/identity-decisions";
import { buildPublicationDrift, type PublicationDriftRow } from "../lib/content-sync/publication-drift";
import type { SubstackAliasRegistry, SubstackPostRegistry } from "../lib/content-sync/schema";

const outDir = path.join(process.cwd(), "reports");

function tally<T extends string>(rows: PublicationDriftRow[], pick: (row: PublicationDriftRow) => T): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const row of rows) counts[pick(row)] = (counts[pick(row)] ?? 0) + 1;
  return counts;
}

function list(counts: Record<string, number>): string {
  return Object.entries(counts).sort().map(([key, n]) => `${key} ${n}`).join(" · ");
}

function main(): void {
  const atlas = getAtlas();
  const atlasEssays = atlas.getPublished("essay").map((entry) => toEssay(entry, atlas));
  const posts = (postsRegistry as SubstackPostRegistry).posts;
  const rows = buildPublicationDrift(atlasEssays, posts, (aliasesRegistry as SubstackAliasRegistry).aliases);
  const pending = (identityDecisions as IdentityDecisionRegistry).pending;

  const summary = {
    atlasRecordsWithSubstack: rows.length,
    assessment: tally(rows, (row) => row.assessment),
    identityBasis: tally(rows, (row) => row.identityBasis),
    title: tally(rows, (row) => row.title.status),
    date: tally(rows, (row) => row.date.status),
    excerpt: tally(rows, (row) => row.excerpt.status),
    substackUrl: tally(rows, (row) => row.substackUrl.status),
    pendingIdentityReviews: pending.length,
  };
  fs.writeFileSync(
    path.join(outDir, "publication-drift.json"),
    `${JSON.stringify({ version: 1, summary, rows, pendingIdentityReviews: pending }, null, 2)}\n`,
    "utf8",
  );

  const flagged = rows.filter((row) => row.assessment !== "in-sync");
  const md = [
    "# Publication drift report",
    "",
    "Generated by `npm run report:publication-drift`. Read-only: signals for editorial review, not decisions. Atlas-authored metadata is never overwritten from this report.",
    "",
    `Atlas essay records with a verified Substack counterpart: **${rows.length}**`,
    "",
    `- Assessment: ${list(summary.assessment)}`,
    `- Identity basis: ${list(summary.identityBasis)}`,
    `- Title: ${list(summary.title)}`,
    `- Date: ${list(summary.date)}`,
    `- Excerpt: ${list(summary.excerpt)}`,
    `- Substack URL: ${list(summary.substackUrl)}`,
    "",
    "`publication-evolution` means identity is established (reviewed alias, authored URL, or exact title + date) and a publication field has since changed. `identity-review-suggested` means the only link is the stored registry mapping and the titles differ. Excerpt differences are counted but do not affect the assessment, because Atlas excerpts are authored.",
    "",
    "## Records with title, date, or URL drift",
    "",
    "| Essay | Basis | Assessment | Title (Atlas → Substack) | Date (Atlas → Substack) | URL |",
    "|---|---|---|---|---|---|",
    ...flagged.map((row) => `| ${row.essayId} \`${row.slug}\` | ${row.identityBasis} | ${row.assessment} | ${row.title.status === "identical" ? "—" : `${row.title.atlas} → ${row.title.substack}`} | ${row.date.status === "identical" ? "—" : `${row.date.atlas} → ${row.date.substack} (${row.date.dayDelta > 0 ? "+" : ""}${row.date.dayDelta}d)`} | ${row.substackUrl.status} |`),
    "",
    "## Pending identity reviews",
    "",
    "Recorded in `data/publications/identity-decisions.json`. These are not Atlas-linked publications; they await a human `same-work` / `distinct-work` decision.",
    "",
    ...pending.map((item) => `- ${item.atlasEssayId} ↔ ${item.registryEssayId} — for: ${item.evidenceFor.join("; ")}. Against: ${item.evidenceAgainst.join("; ")}.`),
    "",
  ].join("\n");
  fs.writeFileSync(path.join(outDir, "publication-drift.md"), md, "utf8");
  console.log(JSON.stringify(summary, null, 2));
}

main();
