/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: every-living-system-pays-a-maintenance-cost.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e3",
  "slug": "every-living-system-pays-a-maintenance-cost",
  "type": "essay",
  "title": "Every Living System Pays a Maintenance Cost",
  "description": "The invisible work that determines whether living systems merely survive — or become.",
  "themes": [
    "th-embodiment",
    "th-structure",
    "th-information",
    "th-consciousness"
  ],
  "parentConcepts": [
    "th-embodiment",
    "th-structure"
  ],
  "connectedItems": [],
  "publishedAt": "2026-07-06",
  "route": "/essays/every-living-system-pays-a-maintenance-cost",
  "status": "published",
  "meta": {
    "subtitle": "The invisible work that determines whether living systems merely survive — or become.",
    "excerpt": "The invisible work that determines whether living systems merely survive — or become.",
    "topics": [
      "Embodiment",
      "Systems",
      "Biology",
      "Maintenance",
      "Capacity"
    ],
    "externalUrl": "https://medium.com/illumination/every-living-system-pays-a-maintenance-cost-7c5f6292dd6d",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e3→p1:chamber",
    "from": "e3",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e3→b1:volume",
    "from": "e3",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e3→th-embodiment:theme",
    "from": "e3",
    "to": "th-embodiment",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches embodiment — the lived body as participant in the real."
  },
  {
    "id": "e3→th-structure:theme",
    "from": "e3",
    "to": "th-structure",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches structure — what holds form while everything changes."
  },
  {
    "id": "e3→th-information:theme",
    "from": "e3",
    "to": "th-information",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches information — signal, structure, and what travels between minds."
  },
  {
    "id": "e3→th-consciousness:theme",
    "from": "e3",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e3→q1:pathway",
    "from": "e3",
    "to": "q1",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What lies beneath perception."
  },
  {
    "id": "e3→e1:echo",
    "from": "e3",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e3→e2:echo",
    "from": "e3",
    "to": "e2",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — You Have to Go Far Enough to Make a Loop."
  },
  {
    "id": "e3→e1:parent",
    "from": "e3",
    "to": "e1",
    "kind": "parent",
    "source": "inferred",
    "weight": 8,
    "rationale": "grows from the earlier essay Constraint Is Not the Opposite of Freedom."
  }
];
