/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: if-you-feel-it-in-your-body-start-here.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e11",
  "slug": "if-you-feel-it-in-your-body-start-here",
  "type": "essay",
  "title": "If You Feel It in Your Body, Start Here",
  "description": "On Who My Work Is For — And Why I Wrote These Books",
  "themes": [
    "th-embodiment",
    "th-identity",
    "th-consciousness",
    "th-relationship"
  ],
  "parentConcepts": [
    "th-embodiment",
    "th-identity"
  ],
  "connectedItems": [],
  "publishedAt": "2026-02-25",
  "route": "/essays/if-you-feel-it-in-your-body-start-here",
  "status": "published",
  "meta": {
    "subtitle": "On Who My Work Is For — And Why I Wrote These Books",
    "excerpt": "On Who My Work Is For — And Why I Wrote These Books",
    "topics": [
      "Embodiment",
      "Nervous System",
      "Orientation",
      "Healing",
      "Systems Thinking"
    ],
    "externalUrl": "https://medium.com/illumination/if-you-feel-it-in-your-body-start-here-7595993ec1fc",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e11→p1:chamber",
    "from": "e11",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e11→b1:volume",
    "from": "e11",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e11→th-embodiment:theme",
    "from": "e11",
    "to": "th-embodiment",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches embodiment — the lived body as participant in the real."
  },
  {
    "id": "e11→th-identity:theme",
    "from": "e11",
    "to": "th-identity",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches identity — the self as ongoing inquiry."
  },
  {
    "id": "e11→th-consciousness:theme",
    "from": "e11",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e11→th-relationship:theme",
    "from": "e11",
    "to": "th-relationship",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches relationship — nothing exists alone."
  },
  {
    "id": "e11→q4:pathway",
    "from": "e11",
    "to": "q4",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: Can language hold the unsayable."
  },
  {
    "id": "e11→e10:echo",
    "from": "e11",
    "to": "e10",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — The Goal Was Never Restriction."
  },
  {
    "id": "e11→e5:echo",
    "from": "e11",
    "to": "e5",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — There Is a Cost to Becoming an Image."
  },
  {
    "id": "e11→e6:echo",
    "from": "e11",
    "to": "e6",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — When Sacrifice Stops Leading Somewhere."
  }
];
