/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: signals-i-m-watching-june-2026.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e8",
  "slug": "signals-i-m-watching-june-2026",
  "type": "essay",
  "title": "Signals I'm Watching — June 2026",
  "description": "People are returning to faith, questioning institutions, craving community, and searching for meaning. I don't know exactly what it means…",
  "themes": [
    "th-meaning",
    "th-relationship",
    "th-time",
    "th-information"
  ],
  "parentConcepts": [
    "th-meaning",
    "th-relationship"
  ],
  "connectedItems": [],
  "publishedAt": "2026-06-09",
  "route": "/essays/signals-i-m-watching-june-2026",
  "status": "published",
  "meta": {
    "subtitle": "People are returning to faith, questioning institutions, craving community, and searching for meaning. I don't know exactly what it means…",
    "excerpt": "People are returning to faith, questioning institutions, craving community, and searching for meaning. I don't know exactly what it means…",
    "topics": [
      "Meaning",
      "Culture",
      "Signals",
      "Observation",
      "Time"
    ],
    "externalUrl": "https://medium.com/@livingterrain/signals-im-watching-june-2026-21299cd7913b",
    "style": "field-digest"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e8→p1:chamber",
    "from": "e8",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e8→th-meaning:theme",
    "from": "e8",
    "to": "th-meaning",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches meaning — how significance accumulates."
  },
  {
    "id": "e8→th-relationship:theme",
    "from": "e8",
    "to": "th-relationship",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches relationship — nothing exists alone."
  },
  {
    "id": "e8→th-time:theme",
    "from": "e8",
    "to": "th-time",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches time — duration as lived, not merely measured."
  },
  {
    "id": "e8→th-information:theme",
    "from": "e8",
    "to": "th-information",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches information — signal, structure, and what travels between minds."
  },
  {
    "id": "e8→q2:pathway",
    "from": "e8",
    "to": "q2",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: How do we inhabit time."
  },
  {
    "id": "e8→q4:pathway",
    "from": "e8",
    "to": "q4",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: Can language hold the unsayable."
  },
  {
    "id": "e8→e2:echo",
    "from": "e8",
    "to": "e2",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — You Have to Go Far Enough to Make a Loop."
  },
  {
    "id": "e8→e4:echo",
    "from": "e8",
    "to": "e4",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — The Ancient Purpose of Looking Up."
  },
  {
    "id": "e8→e3:echo",
    "from": "e8",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  }
];
