/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: the-goal-was-never-restriction.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e10",
  "slug": "the-goal-was-never-restriction",
  "type": "essay",
  "title": "The Goal Was Never Restriction",
  "description": "Healing was supposed to help us participate in life — not become afraid of it.",
  "themes": [
    "th-freedom",
    "th-embodiment",
    "th-identity",
    "th-consciousness"
  ],
  "parentConcepts": [
    "th-freedom",
    "th-embodiment"
  ],
  "connectedItems": [],
  "publishedAt": "2026-06-03",
  "route": "/essays/the-goal-was-never-restriction",
  "status": "published",
  "meta": {
    "subtitle": "Healing was supposed to help us participate in life — not become afraid of it.",
    "excerpt": "Healing was supposed to help us participate in life — not become afraid of it.",
    "topics": [
      "Freedom",
      "Embodiment",
      "Identity",
      "Consciousness"
    ],
    "externalUrl": "https://medium.com/@livingterrain/the-goal-was-never-restriction-195891c84d6d",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e10→p1:chamber",
    "from": "e10",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e10→b1:volume",
    "from": "e10",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e10→th-freedom:theme",
    "from": "e10",
    "to": "th-freedom",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches freedom — constraint, choice, and the shape of a life."
  },
  {
    "id": "e10→th-embodiment:theme",
    "from": "e10",
    "to": "th-embodiment",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches embodiment — the lived body as participant in the real."
  },
  {
    "id": "e10→th-identity:theme",
    "from": "e10",
    "to": "th-identity",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches identity — the self as ongoing inquiry."
  },
  {
    "id": "e10→th-consciousness:theme",
    "from": "e10",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e10→q1:pathway",
    "from": "e10",
    "to": "q1",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What lies beneath perception."
  },
  {
    "id": "e10→e6:echo",
    "from": "e10",
    "to": "e6",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — When Sacrifice Stops Leading Somewhere."
  },
  {
    "id": "e10→e1:echo",
    "from": "e10",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e10→e3:echo",
    "from": "e10",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  }
];
