/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: the-most-important-thing-you-never-learned-about-reality.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e9",
  "slug": "the-most-important-thing-you-never-learned-about-reality",
  "type": "essay",
  "title": "The Most Important Thing You Never Learned About Reality",
  "description": "Your perception does not simply observe reality. It helps create the reality you experience.",
  "themes": [
    "th-reality",
    "th-perception",
    "th-consciousness",
    "th-embodiment"
  ],
  "parentConcepts": [
    "th-reality",
    "th-consciousness"
  ],
  "connectedItems": [],
  "publishedAt": "2026-06-04",
  "route": "/essays/the-most-important-thing-you-never-learned-about-reality",
  "status": "published",
  "meta": {
    "subtitle": "Your perception does not simply observe reality. It helps create the reality you experience.",
    "excerpt": "Your perception does not simply observe reality. It helps create the reality you experience.",
    "topics": [
      "Reality",
      "Consciousness",
      "Embodiment"
    ],
    "externalUrl": "https://medium.com/@livingterrain/the-most-important-thing-you-never-learned-about-reality-28c1e5968940",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e9→p1:chamber",
    "from": "e9",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e9→b1:volume",
    "from": "e9",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e9→th-reality:theme",
    "from": "e9",
    "to": "th-reality",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches reality — what is real before interpretation."
  },
  {
    "id": "e9→th-perception:theme",
    "from": "e9",
    "to": "th-perception",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches perception — what organizes seeing before interpretation."
  },
  {
    "id": "e9→th-consciousness:theme",
    "from": "e9",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e9→th-embodiment:theme",
    "from": "e9",
    "to": "th-embodiment",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches embodiment — the lived body as participant in the real."
  },
  {
    "id": "e9→q1:pathway",
    "from": "e9",
    "to": "q1",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What lies beneath perception."
  },
  {
    "id": "e9→q3:pathway",
    "from": "e9",
    "to": "q3",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What is a place."
  },
  {
    "id": "e9→e7:echo",
    "from": "e9",
    "to": "e7",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — What Happens Before the Tragedy?."
  },
  {
    "id": "e9→e1:echo",
    "from": "e9",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e9→e3:echo",
    "from": "e9",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  }
];
