/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: the-ancient-purpose-of-looking-up.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e4",
  "slug": "the-ancient-purpose-of-looking-up",
  "type": "essay",
  "title": "The Ancient Purpose of Looking Up",
  "description": "Why have human beings returned to this moment in the sky for thousands of years?",
  "themes": [
    "th-time",
    "th-meaning",
    "th-consciousness",
    "th-perception"
  ],
  "parentConcepts": [
    "th-time",
    "th-meaning",
    "th-consciousness"
  ],
  "connectedItems": [],
  "publishedAt": "2026-07-02",
  "route": "/essays/the-ancient-purpose-of-looking-up",
  "status": "published",
  "meta": {
    "subtitle": "Why have human beings returned to this moment in the sky for thousands of years?",
    "excerpt": "Why have human beings returned to this moment in the sky for thousands of years?",
    "topics": [
      "Time",
      "Meaning",
      "Consciousness",
      "Ancient",
      "Strata"
    ],
    "externalUrl": "https://medium.com/readers-digests/the-ancient-purpose-of-looking-up-3429017ac42e",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e4→p1:chamber",
    "from": "e4",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e4→b1:volume",
    "from": "e4",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e4→th-time:theme",
    "from": "e4",
    "to": "th-time",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches time — duration as lived, not merely measured."
  },
  {
    "id": "e4→th-meaning:theme",
    "from": "e4",
    "to": "th-meaning",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches meaning — how significance accumulates."
  },
  {
    "id": "e4→th-consciousness:theme",
    "from": "e4",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e4→th-perception:theme",
    "from": "e4",
    "to": "th-perception",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches perception — what organizes seeing before interpretation."
  },
  {
    "id": "e4→q2:pathway",
    "from": "e4",
    "to": "q2",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: How do we inhabit time."
  },
  {
    "id": "e4→e2:echo",
    "from": "e4",
    "to": "e2",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — You Have to Go Far Enough to Make a Loop."
  },
  {
    "id": "e4→e1:echo",
    "from": "e4",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e4→e3:echo",
    "from": "e4",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  },
  {
    "id": "e4→e1:parent",
    "from": "e4",
    "to": "e1",
    "kind": "parent",
    "source": "inferred",
    "weight": 8,
    "rationale": "grows from the earlier essay Constraint Is Not the Opposite of Freedom."
  }
];
