/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: there-is-a-cost-to-becoming-an-image.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e5",
  "slug": "there-is-a-cost-to-becoming-an-image",
  "type": "essay",
  "title": "There Is a Cost to Becoming an Image",
  "description": "On Britney Spears, social media, and the temptation to trade personhood for visibility",
  "themes": [
    "th-identity",
    "th-consciousness",
    "th-relationship",
    "th-language"
  ],
  "parentConcepts": [
    "th-identity",
    "th-relationship"
  ],
  "connectedItems": [],
  "publishedAt": "2026-06-23",
  "route": "/essays/there-is-a-cost-to-becoming-an-image",
  "status": "published",
  "meta": {
    "subtitle": "On Britney Spears, social media, and the temptation to trade personhood for visibility",
    "excerpt": "On Britney Spears, social media, and the temptation to trade personhood for visibility",
    "topics": [
      "Identity",
      "Image",
      "Performance",
      "Culture",
      "Visibility"
    ],
    "externalUrl": "https://medium.com/readers-digests/there-is-a-cost-to-becoming-an-image-0e174fb767cb",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e5→p1:chamber",
    "from": "e5",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e5→b1:volume",
    "from": "e5",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e5→th-identity:theme",
    "from": "e5",
    "to": "th-identity",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches identity — the self as ongoing inquiry."
  },
  {
    "id": "e5→th-consciousness:theme",
    "from": "e5",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e5→th-relationship:theme",
    "from": "e5",
    "to": "th-relationship",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches relationship — nothing exists alone."
  },
  {
    "id": "e5→th-language:theme",
    "from": "e5",
    "to": "th-language",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches language — what can be carried in words — and what cannot."
  },
  {
    "id": "e5→q1:pathway",
    "from": "e5",
    "to": "q1",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What lies beneath perception."
  },
  {
    "id": "e5→e1:echo",
    "from": "e5",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e5→e2:echo",
    "from": "e5",
    "to": "e2",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — You Have to Go Far Enough to Make a Loop."
  },
  {
    "id": "e5→e3:echo",
    "from": "e5",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  }
];
