/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: what-happens-before-the-tragedy.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e7",
  "slug": "what-happens-before-the-tragedy",
  "type": "essay",
  "title": "What Happens Before the Tragedy?",
  "description": "On fragmentation, formation, and the patterns we fail to see",
  "themes": [
    "th-consciousness",
    "th-perception",
    "th-embodiment",
    "th-information"
  ],
  "parentConcepts": [
    "th-consciousness",
    "th-embodiment"
  ],
  "connectedItems": [],
  "publishedAt": "2026-06-09",
  "route": "/essays/what-happens-before-the-tragedy",
  "status": "published",
  "meta": {
    "subtitle": "On fragmentation, formation, and the patterns we fail to see",
    "excerpt": "On fragmentation, formation, and the patterns we fail to see",
    "topics": [
      "Consciousness",
      "Pattern Recognition",
      "Nervous System",
      "Responsibility",
      "Warning Signs"
    ],
    "externalUrl": "https://medium.com/@livingterrain/what-happens-before-the-tragedy-b07e6c737cd6",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e7→p1:chamber",
    "from": "e7",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e7→b1:volume",
    "from": "e7",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e7→th-consciousness:theme",
    "from": "e7",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e7→th-perception:theme",
    "from": "e7",
    "to": "th-perception",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches perception — what organizes seeing before interpretation."
  },
  {
    "id": "e7→th-embodiment:theme",
    "from": "e7",
    "to": "th-embodiment",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches embodiment — the lived body as participant in the real."
  },
  {
    "id": "e7→th-information:theme",
    "from": "e7",
    "to": "th-information",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches information — signal, structure, and what travels between minds."
  },
  {
    "id": "e7→q1:pathway",
    "from": "e7",
    "to": "q1",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What lies beneath perception."
  },
  {
    "id": "e7→q4:pathway",
    "from": "e7",
    "to": "q4",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: Can language hold the unsayable."
  },
  {
    "id": "e7→e3:echo",
    "from": "e7",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  },
  {
    "id": "e7→e1:echo",
    "from": "e7",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e7→e4:echo",
    "from": "e7",
    "to": "e4",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — The Ancient Purpose of Looking Up."
  }
];
