/**
 * Imported Medium essay — auto-generated by content import.
 * Source intake: when-sacrifice-stops-leading-somewhere.essay.json
 * Do not edit by hand; update intake and re-apply, or use overrides.
 */
import type { AtlasConnection, AtlasEntry } from "../../types";

export const ENTRY: AtlasEntry = {
  "id": "e6",
  "slug": "when-sacrifice-stops-leading-somewhere",
  "type": "essay",
  "title": "When Sacrifice Stops Leading Somewhere",
  "description": "People aren't just questioning wages. They're questioning the exchange itself.",
  "themes": [
    "th-identity",
    "th-consciousness",
    "th-embodiment",
    "th-freedom"
  ],
  "parentConcepts": [
    "th-identity",
    "th-consciousness"
  ],
  "connectedItems": [],
  "publishedAt": "2026-06-15",
  "route": "/essays/when-sacrifice-stops-leading-somewhere",
  "status": "published",
  "meta": {
    "subtitle": "People aren't just questioning wages. They're questioning the exchange itself.",
    "excerpt": "People aren't just questioning wages. They're questioning the exchange itself.",
    "topics": [
      "Identity",
      "Consciousness",
      "Embodiment",
      "Freedom"
    ],
    "externalUrl": "https://medium.com/@livingterrain/when-sacrifice-stops-leading-somewhere-58142a5a7275",
    "style": "essay"
  }
};

export const CONNECTIONS: AtlasConnection[] = [
  {
    "id": "e6→p1:chamber",
    "from": "e6",
    "to": "p1",
    "kind": "chamber",
    "source": "inferred",
    "weight": 9,
    "rationale": "returns to the chamber where this inquiry began."
  },
  {
    "id": "e6→b1:volume",
    "from": "e6",
    "to": "b1",
    "kind": "volume",
    "source": "inferred",
    "weight": 7,
    "rationale": "extends the argument first made in the published volume."
  },
  {
    "id": "e6→th-identity:theme",
    "from": "e6",
    "to": "th-identity",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches identity — the self as ongoing inquiry."
  },
  {
    "id": "e6→th-consciousness:theme",
    "from": "e6",
    "to": "th-consciousness",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches consciousness — the texture of awareness itself."
  },
  {
    "id": "e6→th-embodiment:theme",
    "from": "e6",
    "to": "th-embodiment",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches embodiment — the lived body as participant in the real."
  },
  {
    "id": "e6→th-freedom:theme",
    "from": "e6",
    "to": "th-freedom",
    "kind": "theme",
    "source": "inferred",
    "weight": 7,
    "rationale": "this inquiry also touches freedom — constraint, choice, and the shape of a life."
  },
  {
    "id": "e6→q1:pathway",
    "from": "e6",
    "to": "q1",
    "kind": "pathway",
    "source": "inferred",
    "weight": 8,
    "rationale": "asks the same living question from a different angle: What lies beneath perception."
  },
  {
    "id": "e6→e1:echo",
    "from": "e6",
    "to": "e1",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Constraint Is Not the Opposite of Freedom."
  },
  {
    "id": "e6→e3:echo",
    "from": "e6",
    "to": "e3",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — Every Living System Pays a Maintenance Cost."
  },
  {
    "id": "e6→e5:echo",
    "from": "e6",
    "to": "e5",
    "kind": "echo",
    "source": "inferred",
    "weight": 6,
    "rationale": "echoes nearby work — There Is a Cost to Becoming an Image."
  }
];
